"""PDFBuilder — renders CSRD ESRS E1-6/E1-7 report via WeasyPrint (FR-28).

Usage:
    builder = PDFBuilder()
    pdf_bytes = builder.build(report_data)
    assert pdf_bytes[:4] == b"%PDF"

``report_data`` is a plain dict assembled by ``data_loader.py`` or the
export_service.  No emission calculations are performed here.

ADR-007: Biogenic emissions are NEVER included in Scope 1/2/3 totals.
         They are passed as a separate ``biogenic`` list and rendered
         exclusively in the E1-7 block.

The biogenic disclaimer text is mandatory per constraint #6:
  "Le emissioni biogeniche di CO2 dalla combustione di biomasse e biogas
  sono disclosed separatamente in E1-7. Non sono incluse nei totali
  Scope 1/2/3 ai sensi di ADR-007 e del GHG Protocol Corporate Standard §4.5."
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger(__name__)

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_CSS_PATH = _TEMPLATES_DIR / "styles.css"

DASHBOARD_VERSION = "1.0.0"
DASHBOARD_ID = "esg-main-2026"

_DEFAULT_COMPANY_NAME = "Gruppo Ceramiche Gresmalt S.p.A."


def _company_name() -> str:
    """Return the configured company name (env ``GHG_COMPANY_NAME``)."""
    import os
    return os.getenv("GHG_COMPANY_NAME", "").strip() or _DEFAULT_COMPANY_NAME

_DISCLAIMER_IT = (
    "Questo report è generato automaticamente dal GHG Accounting Tool v1. "
    "I valori sono calcolati secondo il GHG Protocol Corporate Standard (2004) "
    "e ESRS E1 (CSRD). Il report è soggetto a revisione da parte dell'ESG Manager "
    "prima della divulgazione esterna. "
    "Livello di assurance: ISAE 3000 Limited (assurance provider esterno)."
)

_DISCLAIMER_EN = (
    "This report is automatically generated by GHG Accounting Tool v1. "
    "Values are calculated per the GHG Protocol Corporate Standard (2004) "
    "and ESRS E1 (CSRD). The report is subject to review by the ESG Manager "
    "prior to external disclosure. "
    "Assurance level: ISAE 3000 Limited (external assurance provider)."
)


def _get_disclaimer(language: str) -> str:
    """Return the appropriate disclaimer text for the report language.

    Args:
        language: 'it' or 'en'.

    Returns:
        Disclaimer string.
    """
    return _DISCLAIMER_IT if language == "it" else _DISCLAIMER_EN


class PDFBuilder:
    """Renders the CSRD ESRS E1-6/E1-7 PDF report via WeasyPrint.

    The build method receives a ``report_data`` dict containing all
    pre-calculated emission rows, factor catalog entries, DQ findings,
    and audit trail data.  No calculations are performed here.
    """

    def __init__(self) -> None:
        """Initialise PDFBuilder — loads Jinja2 environment once."""
        self._jinja_env: Any = None
        try:
            import jinja2
            self._jinja_env = jinja2.Environment(
                loader=jinja2.FileSystemLoader(str(_TEMPLATES_DIR)),
                autoescape=jinja2.select_autoescape(["html"]),
            )
        except ImportError:
            logger.warning("jinja2 not installed — PDF will use fallback template")

    def build(self, report_data: dict[str, Any]) -> bytes:
        """Generate PDF bytes from report_data.

        Args:
            report_data: Dict with keys:
                - anno: int
                - gwp_set: str
                - language: str ('it' or 'en')
                - emissions: list of emission row dicts (scope 1/2/3)
                - biogenic: list of biogenic memo row dicts (ADR-007)
                - factors: list of factor catalog dicts
                - dq_findings: list of DQ finding dicts
                - audit_trail: list of audit trail dicts
                - intensity_rows: optional list of intensity metric dicts

        Returns:
            PDF bytes starting with ``b'%PDF'``.

        Raises:
            ImportError: If WeasyPrint is not installed.
        """
        import weasyprint

        anno = int(report_data.get("anno", 2025))
        gwp_set = str(report_data.get("gwp_set", "AR6"))
        language = str(report_data.get("language", "it"))
        emissions = list(report_data.get("emissions", []))
        biogenic = list(report_data.get("biogenic", []))
        factors = list(report_data.get("factors", []))
        dq_findings = list(report_data.get("dq_findings", []))
        intensity_rows = list(report_data.get("intensity_rows", []))
        generated_at = datetime.now(UTC).isoformat(timespec="seconds")

        # Separate scope rows
        scope1_rows = [r for r in emissions if r.get("scope") == 1]
        scope2_rows_raw = [r for r in emissions if r.get("scope") == 2]
        scope3_rows_raw = [r for r in emissions if r.get("scope") == 3]

        # Compute scope 2 LB/MB pairs
        scope2_rows = _build_scope2_pairs(scope2_rows_raw)

        # Enrich scope 3 rows with category metadata
        scope3_rows = [_enrich_scope3(r) for r in scope3_rows_raw]

        # Totals (biogenic excluded per ADR-007)
        scope1_total = sum(float(r.get("tco2e") or 0) for r in scope1_rows)
        scope2_lb_total = sum(float(r.get("tco2e_lb") or 0) for r in scope2_rows)
        scope2_mb_total = sum(float(r.get("tco2e_mb") or 0) for r in scope2_rows)
        scope3_total = sum(float(r.get("tco2e") or 0) for r in scope3_rows)

        # Biogenic totals (memo only)
        biogenic_total_co2 = sum(float(r.get("co2_biogenic_tonne", 0)) for r in biogenic)
        biogenic_total_fossil = sum(float(r.get("co2_fossil_tonne", 0)) for r in biogenic)
        has_viano = any(
            r.get("codice_sito") in ("VIANO", "VIANO_GARGOLA")
            for r in emissions
        )

        template_ctx: dict[str, Any] = {
            "anno": anno,
            "gwp_set": gwp_set,
            "language": language,
            "company_name": _company_name(),
            "scope1_rows": scope1_rows,
            "scope2_rows": scope2_rows,
            "scope3_rows": scope3_rows,
            "biogenic_rows": biogenic,
            "factor_rows": factors,
            "dq_rows": dq_findings,
            "intensity_rows": intensity_rows,
            "scope1_total": scope1_total,
            "scope2_lb_total": scope2_lb_total,
            "scope2_mb_total": scope2_mb_total,
            "scope3_total": scope3_total,
            "biogenic_total_co2": biogenic_total_co2,
            "biogenic_total_fossil": biogenic_total_fossil,
            "has_viano": has_viano,
            "generated_at": generated_at,
            "dashboard_id": DASHBOARD_ID,
            "dashboard_version": DASHBOARD_VERSION,
            "disclaimer_text": _get_disclaimer(language),
            "css_path": str(_CSS_PATH),
        }

        html_content = self._render_html(template_ctx)

        log = logger.bind(anno=anno, gwp_set=gwp_set)
        log.info("Rendering PDF via WeasyPrint")

        html_obj = weasyprint.HTML(string=html_content, base_url=str(_TEMPLATES_DIR))
        pdf_bytes: bytes = html_obj.write_pdf()

        log.info("PDF generated", size_bytes=len(pdf_bytes))
        return pdf_bytes

    def _render_html(self, ctx: dict[str, Any]) -> str:
        """Render the HTML template with the given context.

        Falls back to a minimal hardcoded template if Jinja2 is unavailable.

        Args:
            ctx: Template context dict.

        Returns:
            Rendered HTML string.
        """
        if self._jinja_env is not None:
            template = self._jinja_env.get_template("esrs_e1.html")
            return str(template.render(**ctx))
        # Fallback — minimal valid HTML with mandatory metadata
        return _fallback_html(ctx)


def _build_scope2_pairs(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Merge Scope 2 LB and MB rows into site-level pairs.

    Args:
        rows: Raw Scope 2 emission rows.

    Returns:
        List of merged dicts with ``tco2e_lb`` and ``tco2e_mb`` fields.
    """
    from collections import defaultdict
    site_year: dict[tuple[str | None, int | None], dict[str, Any]] = defaultdict(dict)
    for r in rows:
        key = (r.get("codice_sito"), r.get("anno"))
        sub = r.get("sub_scope", "")
        rec = site_year[key]
        rec.setdefault("codice_sito", r.get("codice_sito"))
        rec.setdefault("anno", r.get("anno"))
        rec.setdefault("factor_source", r.get("factor_source", ""))
        rec.setdefault("factor_version", r.get("factor_version", ""))
        rec.setdefault("gwp_set", r.get("gwp_set", "AR6"))
        rec.setdefault("sub_scope", "LB+MB")
        if sub == "LB":
            rec["tco2e_lb"] = float(r.get("tco2e", 0))
        elif sub == "MB":
            rec["tco2e_mb"] = float(r.get("tco2e", 0))
    for rec in site_year.values():
        rec.setdefault("tco2e_lb", None)
        rec.setdefault("tco2e_mb", None)
    return list(site_year.values())


_S3_CAT_NAMES: dict[str, str] = {
    "Cat1": "1 — Beni e servizi acquistati",
    "Cat2": "2 — Beni capitali",
    "Cat3": "3 — Combustibili/energia WTT+T&D",
    "Cat4": "4 — Trasporto upstream",
    "Cat5": "5 — Rifiuti in operazioni",
    "Cat6": "6 — Viaggi di lavoro",
    "Cat7": "7 — Pendolarismo dipendenti",
    "Cat9": "9 — Trasporto downstream",
    "Cat11": "11 — Uso dei prodotti venduti (Omesso — Immateriale)",
    "Cat12": "12 — Fine vita prodotti venduti",
}


def _enrich_scope3(row: dict[str, Any]) -> dict[str, Any]:
    """Add ``category_num`` and ``category_name`` to a Scope 3 row.

    Args:
        row: Scope 3 emission dict.

    Returns:
        Enriched dict.
    """
    import re
    sub = row.get("sub_scope", "")
    m = re.match(r"Cat(\d+)", sub)
    cat_num = m.group(1) if m else "?"
    cat_name = _S3_CAT_NAMES.get(sub, sub)
    return {**row, "category_num": cat_num, "category_name": cat_name}


def _fallback_html(ctx: dict[str, Any]) -> str:
    """Generate a minimal HTML document when Jinja2 is not available.

    Args:
        ctx: Template context dict.

    Returns:
        Minimal HTML string with mandatory metadata.
    """
    anno = ctx["anno"]
    gwp_set = ctx["gwp_set"]
    generated_at = ctx["generated_at"]
    dashboard_id = ctx["dashboard_id"]
    dashboard_version = ctx["dashboard_version"]
    company_name = ctx.get("company_name", _DEFAULT_COMPANY_NAME)

    return f"""<!DOCTYPE html>
<html><head><meta charset='utf-8'>
<title>GHG Report ESRS E1 {anno}</title></head>
<body>
<h1>{company_name} — GHG Report ESRS E1-6 — {anno}</h1>
<p>GWP set: {gwp_set} | Metodologia: GHG Protocol Corporate Standard</p>
<p>Generato: {generated_at} | Dashboard: {dashboard_id} v{dashboard_version}</p>
<p>API v1 | Fonti fattori: ISPRA 2024 + IEA 2024</p>
<p><strong>ADR-007:</strong> Le emissioni biogeniche di CO2 dalla combustione di biomasse
e biogas sono disclosed separatamente in E1-7. Non sono incluse nei totali Scope 1/2/3
ai sensi di ADR-007 e del GHG Protocol Corporate Standard §4.5.</p>
<p><em>Report generato con template di fallback — Jinja2 non disponibile.</em></p>
</body></html>"""
